environment: dev
server:
  port: 8080
spring:
  application:
    name: king
  datasource:
    master:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://localhost:3306/king?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: arongking
      idle-timeout: 10000
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: sg-master
      auto-commit: false
      connection-test-query: SELECT 1
    slave:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://localhost:3306/king?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: arongking
      idle-timeout: 10000
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: sg-slave
      auto-commit: false
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 2000
    database: 0
    max-total: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 8
        min-idle: 1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  resources:
    static-locations: classpath:/public/,classpath:/static/
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html




logging.file: /logs/${spring.application.name}.log
logging:
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    level: debug
  file:
    max-size: 50MB
    max-history: 3

