environment: pre
server:
  port: 8080
spring:
  application:
    name: king
  datasource:
    master:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://localhost:3306/shengong?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      hikari:
        idle-timeout: 10000
        minimum-idle: 1
        maximum-pool-size: 10
        pool-name: sg-master
        auto-commit: false
        connection-test-query: SELECT 1
    slave:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://localhost:3306/king?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      hikari:
        idle-timeout: 10000
        minimum-idle: 1
        maximum-pool-size: 10
        pool-name: sg-slave
        auto-commit: false
        connection-test-query: SELECT 1
  main:
    allow-bean-definition-overriding: true

#mybatis:
#  #指定xml所在的位置
#  mapper-locations: classpath:mapper/*Mapper.xml
#  #指定entity所在的位置
#  type-aliases-package: cn.bj.king.entity


logging.file: /logs/${spring.application.name}.log
logging:
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  file:
    max-size: 50MB
    max-history: 3

